# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy the project files
COPY . /app

# Install the project's dependencies
RUN pip install --no-cache-dir hatchling
RUN pip install --no-cache-dir .

# Set environment variables for Outline authentication
# These should be provided at runtime for security purposes
ENV OUTLINE_URL "https://docs.example.com"
ENV OUTLINE_API_KEY "sk-super-secret-api-key"

# Set the entrypoint command to run the MCP server
ENTRYPOINT ["outline-mcp"]